[package]
name = "volume_fix"
version = "1.0.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Media_Audio",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_Devices_FunctionDiscovery",
    "Win32_System_Com_StructuredStorage",
]